name: Build

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Debug, RelWithDebInfo, Release]
    env:
      PROJECT_NAME: Vkxel

    steps:
      - name: CMake
        uses: lukka/get-cmake@latest

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Generate
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --verbose

      - name: Test
        run: ctest --test-dir build -C ${{ matrix.build_type }} --verbose

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-${{ matrix.build_type }}-${{ matrix.os }}
          path: build/${{ env.PROJECT_NAME }}